name: ONVIF Voice Assistant
version: "1.4.2"
slug: onvif_voice_assistant
description: Voice recognition from ONVIF camera using Wyoming Faster Whisper
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
homeassistant_api: true
map:
  - config:rw
options:
  wyoming_host: "localhost"
  wyoming_port: 10300
  rtsp_url: "rtsp://admin:password@192.168.1.100:554/stream"
  sample_rate: 16000
  channels: 1
  chunk_duration: 2
  vad_enabled: true
  vad_threshold: 0.5
  commands:
    - pattern: "ligar a luz"
      action: "light.turn_on"
      entity_id: "light.sala"
    # Exemplo com múltiplas ações:
    # - pattern: "boa noite"
    #   actions:
    #     - action: "light.turn_off"
    #       entity_id: "light.sala"
    #     - action: "light.turn_off"
    #       entity_id: "light.quarto"
    #     - action: "switch.turn_on"
    #       entity_id: "switch.alarme"
  log_level: "info"
schema:
  wyoming_host: str
  wyoming_port: int
  rtsp_url: str
  sample_rate: int
  channels: int
  chunk_duration: float
  vad_enabled: bool
  vad_threshold: float
  commands: [str]
  log_level: list(debug|info|warning|error)
